services:
#    vladab_base_crm.example:
#        class: Vladab\BaseCRMBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    vladab_base_crm:
      class: Vladab\BaseCRMBundle\BaseCRM\BaseCRM
      arguments: ["%vladabbasecrm.config%"]